# themes from https://github.com/alacritty/alacritty-theme

import = ["~/.config/alacritty/themes/themes/pastel_dark.toml"]
#import = ["~/.config/alacritty/themes/themes/ashes_dark.toml"]
#import = ["~/.config/alacritty/themes/themes/everforest_dark.toml"]

[window]
dimensions = { columns = 120, lines = 90 }
position = { x = 0, y = 0 }
padding = { x = 2, y = 2 }
decorations = "Full"

[font]
size = 17
normal = { family = "UbuntuMono Nerd Font", style = "Regular" }

